"""add parsed_links to tasks

Revision ID: dbd91226f58c
Revises: 138ffd91d3fd
Create Date: 2026-05-13 11:42:30.381526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd91226f58c'
down_revision: Union[str, None] = '138ffd91d3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'parsed_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'conflict_policy',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SKIP', 'OVERWRITE', 'KEEP_BOTH', 'RENAME', name='conflictpolicy'),
               existing_nullable=True,
               existing_server_default=sa.text("'skip'::character varying"))
    op.alter_column('tasks', 'preview_tree',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tasks', 'preview_tree',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tasks', 'conflict_policy',
               existing_type=sa.Enum('SKIP', 'OVERWRITE', 'KEEP_BOTH', 'RENAME', name='conflictpolicy'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'skip'::character varying"))
    op.alter_column('tasks', 'parsed_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###
